### ISSUE TITLE
Which version for local installation?

### ISSUE THREAD

**Issue by adilhasan** [DigitalCurationCentre/DMPonline_v4#158]
Hello, 
I'm trying to do a local installation and am having problems. I tried the v0.5 tag which seems to be the latest, but I think the schema is different to the seeds.rb file. When I run rake db:setup it tells me I need to run rake db:migrate which I do and then rerun rake db:setup and get:

rake aborted!
NoMethodError: undefined method `optional_subset=' for #<GuidanceGroup:0x007f835fcf41a0>
~/code/DMPonline_v4-3/db/seeds.rb:248:in `block in <top (required)>'
~/code/DMPonline_v4-3/db/seeds.rb:244:in `each'
~/code/DMPonline_v4-3/db/seeds.rb:244:in `<top (required)>'
Tasks: TOP => db:setup => db:seed
(See full trace by running task with --trace)

I've tried the HEAD, but that also seems to have problems. Do you have a suggestion?
Many thanks for your help,
adil

**Comment by DigitalCurationCentre** [comment]
Hi Adil,

Sorry you are having problems deploying and running the code. We are aware that there is a problem with the seeds file, and in the next release (May 2015) this should be fixed. 

Thanks to Christian-Albrechts-Universität (CAU), Kiel Germany we have found what was the problem when running running rake db:setup. The problem was on the seeds file, there were parts of the code commented out or missing.

There is a previous seeds file committed that works fine - https://github.com/DigitalCurationCentre/DMPonline_v4/blob/6791c19e751560ac9a18d3bb80f8ff21bc31ff39/db/seeds.rb 

We will be adding documentation in github to support users when downloading and installing MDMPonline

Many thanks,
Marta

**Comment by adilhasan** [comment]
Hello Marta,
many thanks for the quick response. I think this is the same as the one on the wiki? I've tried that one with the v0.5 tag of DMPonline_v4 and the above is the message that I get.  I'm afraid that I'm not fantastic at Ruby. Looking at the app/models/guidance_group.rb I see that there's no method 'optional_subset' defined which I guess is what the error says. I do see it in the HEAD. But, if I try using the HEAD I get a different
error which also leads me to think that the seeds.rb is perhaps not compatible with the HEAD or with the v0.5 tag that I'm using. But, I'm not sure what tag I should use. 
Very much appreciate your help.
adil

**Comment by DigitalCurationCentre** [comment]
Hi Adil,

I'm afraid I don't have a seeds file ready yet. I would suggest to comment out everything from the seeds file and try to run it again.

Sorry, 
Marta

**Comment by adilhasan** [comment]
Hello Marta,
ok I'll give it a bash and see if I can get it to work. Don't worry.
Hope that you have a very great day. 
adil

**Comment by DigitalCurationCentre** [comment]
I'll make a note and when we make the next release available I'll let you know. 
Good luck
Marta
